"""Markdown executive summary report."""

from __future__ import annotations

from pathlib import Path

from doc_analyzer.models import AnalysisResult, CorpusReport

READINESS_ICON = {
    "Ready": "[READY]",
    "Partially Ready": "[PARTIAL]",
    "Requires Restructuring": "[RESTRUCTURE]",
    "Not Ready": "[NOT READY]",
}


def write_markdown_report(report: CorpusReport, output_path: Path) -> Path:
    summary = report.summary
    total = len(report.documents)

    lines: list[str] = [
        "# Document Analysis & Migration Readiness Report",
        "",
        "| | |",
        "|---|---|",
        f"| **Generated** | {report.generated_at} |",
        f"| **Documents analyzed** | {total} |",
        f"| **Analysis engine** | Automated (no API key required) |",
        "",
        "---",
        "",
        "## Key Question",
        "",
        "> **Is this document ready for migration? If not, what needs improvement?**",
        "",
        "See the [Quick Answers](#quick-answers) table below, or open `dashboard.html` for an interactive view.",
        "",
        "---",
        "",
        "## Executive Summary",
        "",
        "| Status | Count |",
        "|--------|-------|",
        f"| Ready | {summary.get('ready_count', 0)} |",
        f"| Partially Ready | {summary.get('partial_count', 0)} |",
        f"| Requires Restructuring | {summary.get('restructure_count', 0)} |",
        f"| Not Ready | {summary.get('not_ready_count', 0)} |",
        "",
        "---",
        "",
        "## Quick Answers",
        "",
        "| Document | Type | Ready? | Readiness | Score | Verdict |",
        "|----------|------|--------|-----------|-------|---------|",
    ]

    for result in report.documents:
        m = result.metrics
        ins = result.insights
        icon = READINESS_ICON.get(ins.migration_readiness, "")
        ready = "Yes" if ins.ready_for_migration else "No"
        verdict_short = ins.migration_verdict.split(".")[0] + "."
        lines.append(
            f"| {m.file_name} | {m.file_type} | {ready} | "
            f"{icon} {ins.migration_readiness} | {ins.migration_score} | {verdict_short} |"
        )

    lines.extend([
        "",
        "---",
        "",
        "## Document Metrics Overview",
        "",
        "| File | Pages | Words | Paragraphs | Headings | Tables | Images |",
        "|------|-------|-------|------------|----------|--------|--------|",
    ])

    for row in summary.get("rows", []):
        result = next(
            (r for r in report.documents if r.metrics.file_name == row["file_name"]),
            None,
        )
        if not result:
            continue
        m = result.metrics
        pages = m.page_count if m.page_count is not None else "-"
        lines.append(
            f"| {row['file_name']} | {pages} | {row['word_count']} | "
            f"{m.paragraph_count} | {row['heading_count']} | {m.table_count} | {m.image_count} |"
        )

    if report.pairs:
        lines.extend([
            "",
            "---",
            "",
            "## DOCX / PDF Pairs",
            "",
            "| Topic | DOCX Words | PDF Words | Content Parity |",
            "|-------|------------|-----------|----------------|",
        ])
        for pair in report.pairs:
            parity = pair.get("parity_ratio", "-")
            if isinstance(parity, float):
                parity = f"{parity * 100:.1f}%"
            lines.append(
                f"| {pair['name']} | {pair.get('docx_words', '-')} | "
                f"{pair.get('pdf_words', '-')} | {parity} |"
            )

    lines.extend([
        "",
        "---",
        "",
        "## Detailed Analysis (Per Document)",
        "",
    ])

    for result in report.documents:
        lines.extend(_document_section(result))

    lines.extend([
        "",
        "---",
        "",
        "## Evaluation Coverage",
        "",
        "| Criterion | How this report addresses it |",
        "|-----------|------------------------------|",
        "| Document parsing accuracy | Extracted via python-docx (DOCX) and PyMuPDF (PDF) |",
        "| Migration-relevant metrics | Pages, words, headings, tables, images, hierarchy issues |",
        "| Automated insights | Readability, clarity, consistency, structural quality, readiness score |",
        "| Practical readiness analysis | Per-file verdict + prioritized improvements |",
        "| Real-world scenarios | Tested on Document360 KB exports (DOCX + PDF pairs) |",
        "",
        "---",
        "",
        "## Output Files",
        "",
        "| File | Description |",
        "|------|-------------|",
        "| `analysis_report.json` | Full structured data (all documents) |",
        "| `documents/*.json` | One JSON file per input document |",
        "| `analysis_report.md` | This summary report |",
        "| `dashboard.html` | Interactive visual dashboard (open in browser) |",
        "",
        "*Generated by Document Analysis & Migration Readiness Tool*",
    ])

    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines), encoding="utf-8")
    return output_path


def _document_section(result: AnalysisResult) -> list[str]:
    m = result.metrics
    ins = result.insights
    icon = READINESS_ICON.get(ins.migration_readiness, "")

    section = [
        f"### {m.file_name}",
        "",
        f"**{icon} {ins.migration_readiness}** | Score: **{ins.migration_score}/100** | Type: {m.file_type}",
        "",
        "#### Is this document ready for migration?",
        "",
        f"**Answer:** {ins.migration_verdict}",
        "",
        "#### Metrics",
        "",
        "| Metric | Value |",
        "|--------|-------|",
        f"| Pages | {m.page_count or 'N/A'} |",
        f"| Words | {m.word_count} |",
        f"| Paragraphs | {m.paragraph_count} |",
        f"| Headings | {m.heading_count} |",
        f"| Tables | {m.table_count} |",
        f"| Images | {m.image_count} |",
        f"| Avg words/paragraph | {m.avg_words_per_paragraph} |",
        f"| Avg sentence length | {m.avg_sentence_length} |",
        "",
        "#### Quality Scores",
        "",
        "| Dimension | Rating |",
        "|-----------|--------|",
        f"| Readability | {ins.readability} |",
        f"| Clarity | {ins.clarity} |",
        f"| Consistency | {ins.consistency} |",
        f"| Structural quality | {ins.structural_quality} |",
        f"| Technical complexity | {ins.technical_complexity} |",
        "",
    ]

    if ins.issues_detected:
        section.extend([
            "#### Issues Detected",
            "",
            *[f"- {issue}" for issue in ins.issues_detected],
            "",
        ])
    else:
        section.extend(["#### Issues Detected", "", "- None detected", ""])

    section.extend([
        "#### What Needs Improvement?",
        "",
    ])
    if ins.suggestions and not ins.ready_for_migration:
        section.extend([f"- {s}" for s in ins.suggestions])
    elif ins.ready_for_migration:
        section.append("- No critical improvements required. Proceed with standard migration checks.")
    else:
        section.extend([f"- {s}" for s in ins.suggestions])

    section.append("")
    return section
