"""Markdown executive summary report."""

from __future__ import annotations

from pathlib import Path

from doc_analyzer.models import AnalysisResult, CorpusReport


def write_markdown_report(report: CorpusReport, output_path: Path) -> Path:
    lines: list[str] = [
        "# Document Analysis & Migration Readiness Report",
        "",
        f"**Generated:** {report.generated_at}  ",
        f"**Input directory:** `{report.input_directory}`  ",
        f"**Documents analyzed:** {len(report.documents)}  ",
        f"**Analysis engine:** Automated (rule-based, no API key required)",
        "",
        "## Executive Summary",
        "",
    ]

    summary = report.summary
    lines.append(f"- **Ready for migration:** {summary.get('ready_count', 0)}")
    lines.append(f"- **Partially ready:** {summary.get('partial_count', 0)}")
    lines.append(f"- **Requires restructuring:** {summary.get('restructure_count', 0)}")
    lines.append(f"- **Not ready:** {summary.get('not_ready_count', 0)}")
    lines.append("")
    lines.append("## Document Overview")
    lines.append("")
    lines.append("| File | Type | Pages | Words | Headings | Readiness | Score |")
    lines.append("|------|------|-------|-------|----------|-----------|-------|")

    for row in summary.get("rows", []):
        pages = row.get("page_count") if row.get("page_count") is not None else "-"
        lines.append(
            f"| {row['file_name']} | {row['file_type']} | {pages} | "
            f"{row['word_count']} | {row['heading_count']} | "
            f"{row['readiness']} | {row['score']} |"
        )

    if report.pairs:
        lines.extend(["", "## DOCX / PDF Pairs", ""])
        lines.append("| Topic | DOCX Words | PDF Words | Parity Ratio |")
        lines.append("|-------|------------|-----------|--------------|")
        for pair in report.pairs:
            lines.append(
                f"| {pair['name']} | {pair.get('docx_words', '-')} | "
                f"{pair.get('pdf_words', '-')} | {pair.get('parity_ratio', '-')} |"
            )

    lines.extend([
        "",
        "## Key Question",
        "",
        "> **Is this document ready for migration? If not, what needs improvement?**",
        "",
    ])

    for result in report.documents:
        lines.extend(_document_section(result))

    lines.extend([
        "",
        "---",
        "",
        "**Output files:**",
        "- `analysis_report.json` - full structured JSON for all documents",
        "- `documents/*.json` - one JSON file per input document",
        "- `analysis_report.md` - this summary report",
        "",
        "*Generated by Document Analysis & Migration Readiness Tool*",
    ])

    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines), encoding="utf-8")
    return output_path


def _document_section(result: AnalysisResult) -> list[str]:
    m = result.metrics
    ins = result.insights
    return [
        "",
        f"## {m.file_name}",
        "",
        "### Is this document ready for migration?",
        "",
        f"**Answer:** {ins.migration_verdict}",
        "",
        "### Metrics",
        f"- **Type:** {m.file_type} | **Size:** {m.size_bytes / 1024:.1f} KB",
        f"- **Pages:** {m.page_count or 'N/A'} | **Words:** {m.word_count} | **Paragraphs:** {m.paragraph_count}",
        f"- **Headings:** {m.heading_count} | **Tables:** {m.table_count} | **Images:** {m.image_count}",
        f"- **Avg words/paragraph:** {m.avg_words_per_paragraph} | **Avg sentence length:** {m.avg_sentence_length}",
        "",
        "### Quality & Readiness",
        f"- **Readability:** {ins.readability}",
        f"- **Clarity:** {ins.clarity}",
        f"- **Consistency:** {ins.consistency}",
        f"- **Structural quality:** {ins.structural_quality}",
        f"- **Technical complexity:** {ins.technical_complexity}",
        f"- **Migration readiness:** **{ins.migration_readiness}** ({ins.migration_score}/100)",
        "",
        "### Issues",
        *(
            [f"- {issue}" for issue in ins.issues_detected]
            if ins.issues_detected
            else ["- None detected"]
        ),
        "",
        "### What needs improvement?",
        *(
            [f"- {s}" for s in ins.suggestions]
            if ins.suggestions
            else ["- No major improvements required"]
        ),
    ]
